//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Features {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class IDescriptorsExtractorSBPattern : IComponentIntrospect {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal IDescriptorsExtractorSBPattern(global::System.IntPtr cPtr, bool cMemoryOwn) : base(solar_api_featuresPINVOKE.IDescriptorsExtractorSBPattern_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IDescriptorsExtractorSBPattern obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          solar_api_featuresPINVOKE.delete_IDescriptorsExtractorSBPattern(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual FrameworkReturnCode extract(ImageList images, Contour2DfArray inContours, DescriptorBuffer descriptors, Contour2DfArray outContours) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_featuresPINVOKE.IDescriptorsExtractorSBPattern_extract__SWIG_0(swigCPtr, ImageList.getCPtr(images), Contour2DfArray.getCPtr(inContours), DescriptorBuffer.getCPtr(descriptors), Contour2DfArray.getCPtr(outContours));
    if (solar_api_featuresPINVOKE.SWIGPendingException.Pending) throw solar_api_featuresPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual FrameworkReturnCode extract(SquaredBinaryPattern pattern, DescriptorBuffer descriptor) {
    FrameworkReturnCode ret = (FrameworkReturnCode)solar_api_featuresPINVOKE.IDescriptorsExtractorSBPattern_extract__SWIG_1(swigCPtr, SquaredBinaryPattern.getCPtr(pattern), DescriptorBuffer.getCPtr(descriptor));
    if (solar_api_featuresPINVOKE.SWIGPendingException.Pending) throw solar_api_featuresPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
