//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Datastructure {

    //using XPCF.Core;
    using SolAR.Core;

public class CameraParameters : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal CameraParameters(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CameraParameters obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~CameraParameters() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          solar_datastructurePINVOKE.delete_CameraParameters(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p_Sizei resolution {
    set {
      solar_datastructurePINVOKE.CameraParameters_resolution_set(swigCPtr, SWIGTYPE_p_Sizei.getCPtr(value));
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      SWIGTYPE_p_Sizei ret = new SWIGTYPE_p_Sizei(solar_datastructurePINVOKE.CameraParameters_resolution_get(swigCPtr), true);
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Matrix3x3f intrinsic {
    set {
      solar_datastructurePINVOKE.CameraParameters_intrinsic_set(swigCPtr, Matrix3x3f.getCPtr(value));
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      Matrix3x3f ret = new Matrix3x3f(solar_datastructurePINVOKE.CameraParameters_intrinsic_get(swigCPtr), true);
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public Vector5f distorsion {
    set {
      solar_datastructurePINVOKE.CameraParameters_distorsion_set(swigCPtr, Vector5f.getCPtr(value));
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      Vector5f ret = new Vector5f(solar_datastructurePINVOKE.CameraParameters_distorsion_get(swigCPtr), true);
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public CameraParameters() : this(solar_datastructurePINVOKE.new_CameraParameters(), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

}

}
