//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Datastructure {

public enum DescriptorType {
  AKAZE,
  SIFT,
  SURF_64,
  SURF_128,
  ORB,
  SBPATTERN
}

}
