//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Datastructure {

    //using XPCF.Core;
    using SolAR.Core;

public class Keyframe : Frame {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal Keyframe(global::System.IntPtr cPtr, bool cMemoryOwn) : base(solar_datastructurePINVOKE.Keyframe_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Keyframe obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          solar_datastructurePINVOKE.delete_Keyframe(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public Keyframe(Frame frame) : this(solar_datastructurePINVOKE.new_Keyframe__SWIG_0(Frame.getCPtr(frame)), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public Keyframe(KeypointArray keypoints, DescriptorBuffer descriptors, Image view, Keyframe refKeyframe, Transform3Df pose) : this(solar_datastructurePINVOKE.new_Keyframe__SWIG_1(KeypointArray.getCPtr(keypoints), DescriptorBuffer.getCPtr(descriptors), Image.getCPtr(view), Keyframe.getCPtr(refKeyframe), Transform3Df.getCPtr(pose)), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public Keyframe(KeypointArray keypoints, DescriptorBuffer descriptors, Image view, Keyframe refKeyframe) : this(solar_datastructurePINVOKE.new_Keyframe__SWIG_2(KeypointArray.getCPtr(keypoints), DescriptorBuffer.getCPtr(descriptors), Image.getCPtr(view), Keyframe.getCPtr(refKeyframe)), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public Keyframe(KeypointArray keypoints, DescriptorBuffer descriptors, Image view, Transform3Df pose) : this(solar_datastructurePINVOKE.new_Keyframe__SWIG_3(KeypointArray.getCPtr(keypoints), DescriptorBuffer.getCPtr(descriptors), Image.getCPtr(view), Transform3Df.getCPtr(pose)), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public Keyframe(KeypointArray keypoints, DescriptorBuffer descriptors, Image view) : this(solar_datastructurePINVOKE.new_Keyframe__SWIG_4(KeypointArray.getCPtr(keypoints), DescriptorBuffer.getCPtr(descriptors), Image.getCPtr(view)), true) {
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public MapIntInt getNeighborKeyframes() {
    MapIntInt ret = new MapIntInt(solar_datastructurePINVOKE.Keyframe_getNeighborKeyframes(swigCPtr), false);
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public UIntVector getBestNeighborKeyframes(int nbKeyframes) {
    UIntVector ret = new UIntVector(solar_datastructurePINVOKE.Keyframe_getBestNeighborKeyframes(swigCPtr, nbKeyframes), true);
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void addNeighborKeyframe(uint idxKeyframe, uint weight) {
    solar_datastructurePINVOKE.Keyframe_addNeighborKeyframe(swigCPtr, idxKeyframe, weight);
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public static void resetFirstIdKeyframe() {
    solar_datastructurePINVOKE.Keyframe_resetFirstIdKeyframe();
    if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
  }

  public int m_idx {
    set {
      solar_datastructurePINVOKE.Keyframe_m_idx_set(swigCPtr, value);
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      int ret = solar_datastructurePINVOKE.Keyframe_m_idx_get(swigCPtr);
      if (solar_datastructurePINVOKE.SWIGPendingException.Pending) throw solar_datastructurePINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

}

}
