//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Tracking {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class FloatList : global::System.IDisposable, global::System.Collections.IEnumerable, global::System.Collections.Generic.IList<float>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal FloatList(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(FloatList obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~FloatList() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          solar_api_trackingPINVOKE.delete_FloatList(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public FloatList(global::System.Collections.IEnumerable c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (float element in c) {
      this.Add(element);
    }
  }

  public FloatList(global::System.Collections.Generic.IEnumerable<float> c) : this() {
    if (c == null)
      throw new global::System.ArgumentNullException("c");
    foreach (float element in c) {
      this.Add(element);
    }
  }

  public bool IsFixedSize {
    get {
      return false;
    }
  }

  public bool IsReadOnly {
    get {
      return false;
    }
  }

  public float this[int index]  {
    get {
      return getitem(index);
    }
    set {
      setitem(index, value);
    }
  }

  public int Capacity {
    get {
      return (int)capacity();
    }
    set {
      if (value < size())
        throw new global::System.ArgumentOutOfRangeException("Capacity");
      reserve((uint)value);
    }
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsSynchronized {
    get {
      return false;
    }
  }

  public void CopyTo(float[] array)
  {
    CopyTo(0, array, 0, this.Count);
  }

  public void CopyTo(float[] array, int arrayIndex)
  {
    CopyTo(0, array, arrayIndex, this.Count);
  }

  public void CopyTo(int index, float[] array, int arrayIndex, int count)
  {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (index < 0)
      throw new global::System.ArgumentOutOfRangeException("index", "Value is less than zero");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (count < 0)
      throw new global::System.ArgumentOutOfRangeException("count", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (index+count > this.Count || arrayIndex+count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");
    for (int i=0; i<count; i++)
      array.SetValue(getitemcopy(index+i), arrayIndex+i);
  }

  public float[] ToArray() {
    float[] array = new float[this.Count];
    this.CopyTo(array);
    return array;
  }

  global::System.Collections.Generic.IEnumerator<float> global::System.Collections.Generic.IEnumerable<float>.GetEnumerator() {
    return new FloatListEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new FloatListEnumerator(this);
  }

  public FloatListEnumerator GetEnumerator() {
    return new FloatListEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class FloatListEnumerator : global::System.Collections.IEnumerator
    , global::System.Collections.Generic.IEnumerator<float>
  {
    private FloatList collectionRef;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public FloatListEnumerator(FloatList collection) {
      collectionRef = collection;
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public float Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (float)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        currentObject = collectionRef[currentIndex];
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
        currentIndex = -1;
        currentObject = null;
    }
  }

  public void Clear() {
    solar_api_trackingPINVOKE.FloatList_Clear(swigCPtr);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Add(float x) {
    solar_api_trackingPINVOKE.FloatList_Add(swigCPtr, x);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = solar_api_trackingPINVOKE.FloatList_size(swigCPtr);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private uint capacity() {
    uint ret = solar_api_trackingPINVOKE.FloatList_capacity(swigCPtr);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void reserve(uint n) {
    solar_api_trackingPINVOKE.FloatList_reserve(swigCPtr, n);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatList() : this(solar_api_trackingPINVOKE.new_FloatList__SWIG_0(), true) {
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatList(FloatList other) : this(solar_api_trackingPINVOKE.new_FloatList__SWIG_1(FloatList.getCPtr(other)), true) {
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatList(int capacity) : this(solar_api_trackingPINVOKE.new_FloatList__SWIG_2(capacity), true) {
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  private float getitemcopy(int index) {
    float ret = solar_api_trackingPINVOKE.FloatList_getitemcopy(swigCPtr, index);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private float getitem(int index) {
    float ret = solar_api_trackingPINVOKE.FloatList_getitem(swigCPtr, index);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(int index, float val) {
    solar_api_trackingPINVOKE.FloatList_setitem(swigCPtr, index, val);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void AddRange(FloatList values) {
    solar_api_trackingPINVOKE.FloatList_AddRange(swigCPtr, FloatList.getCPtr(values));
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public FloatList GetRange(int index, int count) {
    global::System.IntPtr cPtr = solar_api_trackingPINVOKE.FloatList_GetRange(swigCPtr, index, count);
    FloatList ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatList(cPtr, true);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Insert(int index, float x) {
    solar_api_trackingPINVOKE.FloatList_Insert(swigCPtr, index, x);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void InsertRange(int index, FloatList values) {
    solar_api_trackingPINVOKE.FloatList_InsertRange(swigCPtr, index, FloatList.getCPtr(values));
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveAt(int index) {
    solar_api_trackingPINVOKE.FloatList_RemoveAt(swigCPtr, index);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void RemoveRange(int index, int count) {
    solar_api_trackingPINVOKE.FloatList_RemoveRange(swigCPtr, index, count);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public static FloatList Repeat(float value, int count) {
    global::System.IntPtr cPtr = solar_api_trackingPINVOKE.FloatList_Repeat(value, count);
    FloatList ret = (cPtr == global::System.IntPtr.Zero) ? null : new FloatList(cPtr, true);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Reverse() {
    solar_api_trackingPINVOKE.FloatList_Reverse__SWIG_0(swigCPtr);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void Reverse(int index, int count) {
    solar_api_trackingPINVOKE.FloatList_Reverse__SWIG_1(swigCPtr, index, count);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public void SetRange(int index, FloatList values) {
    solar_api_trackingPINVOKE.FloatList_SetRange(swigCPtr, index, FloatList.getCPtr(values));
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Contains(float value) {
    bool ret = solar_api_trackingPINVOKE.FloatList_Contains(swigCPtr, value);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int IndexOf(float value) {
    int ret = solar_api_trackingPINVOKE.FloatList_IndexOf(swigCPtr, value);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public int LastIndexOf(float value) {
    int ret = solar_api_trackingPINVOKE.FloatList_LastIndexOf(swigCPtr, value);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool Remove(float value) {
    bool ret = solar_api_trackingPINVOKE.FloatList_Remove(swigCPtr, value);
    if (solar_api_trackingPINVOKE.SWIGPendingException.Pending) throw solar_api_trackingPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
