//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace SolAR.Api.Display {

    using XPCF.Api;
    using SolAR.Core;
    using SolAR.Datastructure;

public class I2DOverlay : IComponentIntrospect {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  private bool swigCMemOwnDerived;

  internal I2DOverlay(global::System.IntPtr cPtr, bool cMemoryOwn) : base(solar_api_displayPINVOKE.I2DOverlay_SWIGSmartPtrUpcast(cPtr), true) {
    swigCMemOwnDerived = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(I2DOverlay obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwnDerived) {
          swigCMemOwnDerived = false;
          solar_api_displayPINVOKE.delete_I2DOverlay(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual void drawCircle(Point2Df point, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawCircle(swigCPtr, Point2Df.getCPtr(point), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircles(Point2DfArray points, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawCircles__SWIG_0(swigCPtr, Point2DfArray.getCPtr(points), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void drawCircles(KeypointArray keypoints, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawCircles__SWIG_1(swigCPtr, KeypointArray.getCPtr(keypoints), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void drawContour(Point2DfArray contours, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawContour(swigCPtr, Point2DfArray.getCPtr(contours), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void drawContours(Contour2DfArray contours, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawContours(swigCPtr, Contour2DfArray.getCPtr(contours), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void drawSBPattern(SquaredBinaryPattern pattern, Image displayImage) {
    solar_api_displayPINVOKE.I2DOverlay_drawSBPattern(swigCPtr, SquaredBinaryPattern.getCPtr(pattern), Image.getCPtr(displayImage));
    if (solar_api_displayPINVOKE.SWIGPendingException.Pending) throw solar_api_displayPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
