//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Api {

    using XPCF.Core;
    using XPCF.Collection;
    using XPCF.Properties;
    using XPCF.Traits;

public class InterfaceNotImplementedException : Exception {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal InterfaceNotImplementedException(global::System.IntPtr cPtr, bool cMemoryOwn) : base(xpcf_apiPINVOKE.InterfaceNotImplementedException_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(InterfaceNotImplementedException obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          xpcf_apiPINVOKE.delete_InterfaceNotImplementedException(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public InterfaceNotImplementedException(UUID componentUUID, UUID interfaceUUID) : this(xpcf_apiPINVOKE.new_InterfaceNotImplementedException__SWIG_0(UUID.getCPtr(componentUUID), UUID.getCPtr(interfaceUUID)), true) {
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
  }

  public InterfaceNotImplementedException(string what) : this(xpcf_apiPINVOKE.new_InterfaceNotImplementedException__SWIG_1(what), true) {
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
