//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.1
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace XPCF.Api {

	using XPCF.Core;
    using XPCF.Collection;
    using XPCF.Properties;
    using XPCF.Traits;

public class xpcf_api {
  public static IComponentManager getComponentManagerInstance() {
    global::System.IntPtr cPtr = xpcf_apiPINVOKE.getComponentManagerInstance();
    IComponentManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new IComponentManager(cPtr, true);
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static IComponentIntrospect createInstance(UUID componentUUID) {
    global::System.IntPtr cPtr = xpcf_apiPINVOKE.createInstance__SWIG_0(UUID.getCPtr(componentUUID));
    IComponentIntrospect ret = (cPtr == global::System.IntPtr.Zero) ? null : new IComponentIntrospect(cPtr, true);
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static IComponentIntrospect createInstance(string instanceName, UUID componentUUID) {
    global::System.IntPtr cPtr = xpcf_apiPINVOKE.createInstance__SWIG_1(instanceName, UUID.getCPtr(componentUUID));
    IComponentIntrospect ret = (cPtr == global::System.IntPtr.Zero) ? null : new IComponentIntrospect(cPtr, true);
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static IModuleManager getModuleManagerInstance() {
    global::System.IntPtr cPtr = xpcf_apiPINVOKE.getModuleManagerInstance();
    IModuleManager ret = (cPtr == global::System.IntPtr.Zero) ? null : new IModuleManager(cPtr, true);
    if (xpcf_apiPINVOKE.SWIGPendingException.Pending) throw xpcf_apiPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
